version: '3.9'
name: park-nav-finder

services:
  user_postgres:
    image: postgres:15.1
    container_name: user_postgres
    restart: always
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - 5501:5432
    volumes:
      - users-pg-data:/var/lib/postgresql/data

volumes:
  users-pg-data:
    driver: local
