@UserService_HostAddress = http://localhost:5001

###
# Register
POST {{UserService_HostAddress}}/identity/register
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "YourPassword"
}

###
# Login
POST {{UserService_HostAddress}}/identity/login
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "YourPassword"
}

###
# Refresh Token
POST {{UserService_HostAddress}}/identity/refresh
Content-Type: application/json

{
  "refreshToken": "YourRefreshToken"
}

###
